services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=rc-admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    restart: always